ALTER TABLE `cars`
ADD COLUMN `exterior_color` VARCHAR(45) NULL AFTER `modified_by`,
ADD COLUMN `power_steering` VARCHAR(45) NULL AFTER `exterior_color`,
ADD COLUMN `air_condition` VARCHAR(45) NULL AFTER `power_steering`,
ADD COLUMN `alloy_wheel` VARCHAR(45) NULL AFTER `air_condition`,
ADD COLUMN `interior_color` VARCHAR(45) NULL AFTER `alloy_wheel`,
ADD COLUMN `tv` VARCHAR(45) NULL AFTER `interior_color`,
ADD COLUMN `keyless_entry` VARCHAR(45) NULL AFTER `tv`,
ADD COLUMN `aero_kit` VARCHAR(45) NULL AFTER `keyless_entry`,
ADD COLUMN `rear_parking_camera` VARCHAR(45) NULL AFTER `aero_kit`,
ADD COLUMN `power_door` VARCHAR(45) NULL AFTER `rear_parking_camera`,
ADD COLUMN `seat_heater` VARCHAR(45) NULL AFTER `power_door`,
ADD COLUMN `spare_key` VARCHAR(45) NULL AFTER `seat_heater`,
ADD COLUMN `roof_rails` VARCHAR(45) NULL AFTER `spare_key`,
ADD COLUMN `parking_sensor` VARCHAR(45) NULL AFTER `roof_rails`,
ADD COLUMN `power_window` VARCHAR(45) NULL AFTER `parking_sensor`,
ADD COLUMN `power_seats` VARCHAR(45) NULL AFTER `power_window`,
ADD COLUMN `maintenance_record` VARCHAR(45) NULL AFTER `power_seats`,
ADD COLUMN `anti_break_system` VARCHAR(45) NULL AFTER `maintenance_record`,
ADD COLUMN `airbags` VARCHAR(45) NULL AFTER `anti_break_system`,
ADD COLUMN `navigation` VARCHAR(45) NULL AFTER `airbags`,
ADD COLUMN `cd_player` VARCHAR(45) NULL AFTER `navigation`,
ADD COLUMN `sliding_door` VARCHAR(45) NULL AFTER `cd_player`,
ADD COLUMN `smart_key_system` VARCHAR(45) NULL AFTER `sliding_door`,
ADD COLUMN `automatic_door` VARCHAR(45) NULL AFTER `smart_key_system`,
ADD COLUMN `low_down` VARCHAR(45) NULL AFTER `automatic_door`,
ADD COLUMN `body_kit` VARCHAR(45) NULL AFTER `low_down`,
ADD COLUMN `rear_spoiler` VARCHAR(45) NULL AFTER `body_kit`,
ADD COLUMN `wind_breaker` VARCHAR(45) NULL AFTER `rear_spoiler`,
ADD COLUMN `seating_capacity` VARCHAR(45) NULL AFTER `wind_breaker`,
ADD COLUMN `no_smoking` VARCHAR(45) NULL AFTER `seating_capacity`,
ADD COLUMN `one_owner` VARCHAR(45) NULL AFTER `no_smoking`,
ADD COLUMN `anti_theft_system` VARCHAR(45) NULL AFTER `one_owner`,
ADD COLUMN `leather_seats` VARCHAR(45) NULL AFTER `anti_theft_system`,
ADD COLUMN `light` VARCHAR(45) NULL AFTER `leather_seats`,
ADD COLUMN `md_changer` VARCHAR(45) NULL AFTER `light`,
ADD COLUMN `bench_seats` VARCHAR(45) NULL AFTER `md_changer`,
ADD COLUMN `double_air_condition` VARCHAR(45) NULL AFTER `bench_seats`,
ADD COLUMN `sunroof` VARCHAR(45) NULL AFTER `double_air_condition`,
ADD COLUMN `electronic_stability_control` VARCHAR(45) NULL AFTER `sunroof`,
ADD COLUMN `spare_tyre` VARCHAR(45) NULL AFTER `electronic_stability_control`,
ADD COLUMN `fog_lamp` VARCHAR(45) NULL AFTER `spare_tyre`,
ADD COLUMN `mud_flap` VARCHAR(45) NULL AFTER `fog_lamp`;


ALTER TABLE `cars` ADD COLUMN `remarks` TEXT NULL AFTER `mud_flap`;